title: TexTome
description: A Template for LaTeX Reports
show_downloads: true
theme: jekyll-theme-merlot
github:
  zip_url: https://github.com/The-Trustworthy/TexTome/zipball/release
  tar_url: https://github.com/The-Trustworthy/TexTome/tarball/release
  another_url: https://ravi-prakash1907.gitlab.io/
