title: TexTome
description: A Template for LaTeX Reports
show_downloads: true
theme: jekyll-theme-merlot
github:
  zip_url: https://github.com/ravi-prakash1907/TexTome/zipball/release
  tar_url: https://github.com/ravi-prakash1907/TexTome/tarball/release
  another_url: https://raviprakash.cf/
